### ISSUE TITLE
docker file?

### ISSUE THREAD

**Issue by antipasta** [svanhoutte/wyze_garmin_sync#1]
Hi,

Was looking at how to sync data from my wyze scale to garmin connect and came across this repo. Are you planning on committing the docker file that generates the image?

**Comment by svanhoutte** [comment]
Hello 

I m redoing the code and I should be able to update everything today or across the weekend. I m not sure the docker will be necessary in the future.

**Comment by antipasta** [comment]
sounds good! honestly the docker file sounds great to me if it automatically installs all dependencies etc in the image.

**Comment by svanhoutte** [comment]
No problem i ll keep a docker with it :)

**Comment by svanhoutte** [comment]
Docker and repo updated you can give it a try now. 
Please use docker compose file

**Comment by antipasta** [comment]
Hi,

Typically a Dockerfile is included so that way users can build the image themselves if they prefer, so that way they know exactly what is included in the container they'll be running. Especially in this case where credentials are involved. Any chance you can commit that alongside the docker-compose?

**Comment by svanhoutte** [comment]
I attached the dockerfile and required files in the docker 
 files directory 
https://github.com/svanhoutte/wyze_garmin_sync/tree/main/Docker%20files

**Comment by antipasta** [comment]
thanks for committing the docker file, very helpful!

**Comment by svanhoutte** [comment]
files uploaded
