### ISSUE TITLE
Hi, it's me again...

### ISSUE THREAD

**Issue by eueyrunbike** [svanhoutte/wyze_garmin_sync#10]
So about 2 week ago something broke. I no longer had it syncing to connect. I tried fumbling around and ended up just trying to start over including reauthenticating for the two factor code on wyze. I forget where I should place the files in your repo when I download them. Should I place them in the Docker folder or just anywhere like the desktop? When I tried to compose up again, I got errors...Sorry I'm just not computer literate enough to understand and troubleshoot for myself. Any help is appreciated. Docker is updated to the latest version as well. Thanks so much!

PS C:\users\monica\.docker> docker-compose up
[+] Running 1/1
 ✔ Container docker-wyzegarminconnect-1  Created                                                                   0.3s
Attaching to docker-wyzegarminconnect-1
docker-wyzegarminconnect-1  | /wyze_garmin_sync /wyze_garmin_sync
docker-wyzegarminconnect-1  | Traceback (most recent call last):
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 200, in _new_conn
docker-wyzegarminconnect-1  |     sock = connection.create_connection(
docker-wyzegarminconnect-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
docker-wyzegarminconnect-1  |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
docker-wyzegarminconnect-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
docker-wyzegarminconnect-1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
docker-wyzegarminconnect-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  | socket.gaierror: [Errno -3] Temporary failure in name resolution
docker-wyzegarminconnect-1  |
docker-wyzegarminconnect-1  | The above exception was the direct cause of the following exception:
docker-wyzegarminconnect-1  |
docker-wyzegarminconnect-1  | Traceback (most recent call last):
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
docker-wyzegarminconnect-1  |
docker-wyzegarminconnect-1  |     response = self._make_request(
docker-wyzegarminconnect-1  |                ^^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
docker-wyzegarminconnect-1  |     raise new_e
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
docker-wyzegarminconnect-1  |     self._validate_conn(conn)
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
docker-wyzegarminconnect-1  |     conn.connect()
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 604, in connect
docker-wyzegarminconnect-1  |     self.sock = sock = self._new_conn()
docker-wyzegarminconnect-1  |                        ^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 207, in _new_conn
docker-wyzegarminconnect-1  |     raise NameResolutionError(self.host, self, e) from e
docker-wyzegarminconnect-1  | urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f3e51f73210>: Failed to resolve 'auth-prod.api.wyze.com' ([Errno -3] Temporary failure in name resolution)
docker-wyzegarminconnect-1  |
docker-wyzegarminconnect-1  | The above exception was the direct cause of the following exception:
docker-wyzegarminconnect-1  |
docker-wyzegarminconnect-1  | Traceback (most recent call last):
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
docker-wyzegarminconnect-1  |
docker-wyzegarminconnect-1  |     resp = conn.urlopen(
docker-wyzegarminconnect-1  |            ^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
docker-wyzegarminconnect-1  |     retries = retries.increment(
docker-wyzegarminconnect-1  |               ^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
docker-wyzegarminconnect-1  |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
docker-wyzegarminconnect-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='auth-prod.api.wyze.com', port=443): Max retries exceeded with url: /user/login (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3e51f73210>: Failed to resolve 'auth-prod.api.wyze.com' ([Errno -3] Temporary failure in name resolution)"))
docker-wyzegarminconnect-1  |
docker-wyzegarminconnect-1  | During handling of the above exception, another exception occurred:
docker-wyzegarminconnect-1  |
docker-wyzegarminconnect-1  | Traceback (most recent call last):
docker-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 17, in <module>
docker-wyzegarminconnect-1  |
docker-wyzegarminconnect-1  |     client = Client(email=os.environ['WYZE_EMAIL'], password=os.environ['WYZE_PASSWORD'], totp_key=os.environ['WYZE_TOTP'])
docker-wyzegarminconnect-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/api/client.py", line 66, in __init__
docker-wyzegarminconnect-1  |     self.login()
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/api/client.py", line 164, in login
docker-wyzegarminconnect-1  |     response = self._auth_client().user_login(email=self._email, password=self._password, totp_key=self._totp_key)
docker-wyzegarminconnect-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/auth_service.py", line 75, in user_login
docker-wyzegarminconnect-1  |     response = self.api_call('/user/login', json=kwargs, nonce=nonce)
docker-wyzegarminconnect-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/auth_service.py", line 56, in api_call
docker-wyzegarminconnect-1  |     return super().api_call(
docker-wyzegarminconnect-1  |            ^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/base.py", line 347, in api_call
docker-wyzegarminconnect-1  |     return super().api_call(
docker-wyzegarminconnect-1  |            ^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/base.py", line 204, in api_call
docker-wyzegarminconnect-1  |     return self.do_post(url=api_url, headers=headers, payload=json, params=params)
docker-wyzegarminconnect-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/base.py", line 132, in do_post
docker-wyzegarminconnect-1  |     return self._do_request(client, req)
docker-wyzegarminconnect-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/base.py", line 109, in _do_request
docker-wyzegarminconnect-1  |     raise e
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/base.py", line 91, in _do_request
docker-wyzegarminconnect-1  |     response = session.send(request, **settings)
docker-wyzegarminconnect-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
docker-wyzegarminconnect-1  |     r = adapter.send(request, **kwargs)
docker-wyzegarminconnect-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
docker-wyzegarminconnect-1  |     raise ConnectionError(e, request=request)
docker-wyzegarminconnect-1  | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='auth-prod.api.wyze.com', port=443): Max retries exceeded with url: /user/login (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3e51f73210>: Failed to resolve 'auth-prod.api.wyze.com' ([Errno -3] Temporary failure in name resolution)"))
docker-wyzegarminconnect-1  | md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
docker-wyzegarminconnect-1  | 2023-07-27 19:27:20,715 [WARNING] File '/wyze_garmin_sync/wyze_scale.fit' does not exist. Skipping...
docker-wyzegarminconnect-1  | Error: No valid files.
docker-wyzegarminconnect-1  | file not uploaded

**Comment by svanhoutte** [comment]
Hello, 

I m looking into it. 
Thanks

**Comment by svanhoutte** [comment]
Ok found the issue, this is linked to the way Wyze request authentication now 
I made some test this evening and was able to make it work
You have to go to the https://developer-api-console.wyze.com/#/apikey/view
and create your api key then update WYZE_KEY_ID and WYZE_API_KEY when i ll have updated the file in the rep.

**Comment by eueyrunbike** [comment]
Hi. I see the updated files. I downloaded the zip again. I am unsure where to unzip them. I found a folder that says ".docker" so i just unloaded them there. I followed instructions for the api id and key and edited the docker-compose file. Opened powershell for the compose up and got errors. 

PS C:\Users\Monica\.docker> docker-compose up
[+] Running 1/1
 ✔ Container docker-wyzegarminconnect-1  Created                                                                   1.3s
Attaching to docker-wyzegarminconnect-1
docker-wyzegarminconnect-1  | "/etc/cron.d/garmin_wyze_scheduler":3: bad minute
docker-wyzegarminconnect-1  | errors in crontab file, can't install.
docker-wyzegarminconnect-1  | /wyze_garmin_sync /wyze_garmin_sync
docker-wyzegarminconnect-1  | Traceback (most recent call last):
docker-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 17, in <module>
docker-wyzegarminconnect-1  |     client = Client(email=os.environ['WYZE_EMAIL'], password=os.environ['WYZE_PASSWORD'], totp_key=os.environ['WYZE_TOTP'])
docker-wyzegarminconnect-1  |                                                                                                    ~~~~~~~~~~^^^^^^^^^^^^^
docker-wyzegarminconnect-1  |   File "<frozen os>", line 679, in __getitem__
docker-wyzegarminconnect-1  | KeyError: 'WYZE_TOTP'
docker-wyzegarminconnect-1  | md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
docker-wyzegarminconnect-1  | 2023-07-30 17:04:30,691 [WARNING] File '/wyze_garmin_sync/wyze_scale.fit' does not exist. Skipping...
docker-wyzegarminconnect-1  | Error: No valid files.
docker-wyzegarminconnect-1  | file not uploaded

Thanks for looking into it. I'm glad to know I didn't do something wrong to break the cycle!

**Comment by svanhoutte** [comment]
Hello 

1st go to https://developer-api-console.wyze.com/#/apikey/view 
login and get your key and ID. Keep them you ll need them after. 
2nd get the latest version of the tool and extract the docker-compose.yml 
3rd Enter your credentials in the new docker-compose.yml file including the Key and ID from #1 
4th in the same directory as your new docker-compose.yml file run : docker compose pull 
5th in the same directory as your new docker-compose.yml file run : docker compose up --force-recreate --build -d --remove-orphans
6th in the same directory as your new docker-compose.yml file run : docker compose logs -f 

Let me know how that works 
Good luck

**Comment by eueyrunbike** [comment]
Did that to the T and everything worked instantly. Still don't understand how all this works, but thanks! Until Garmin picks up their game on a new scale, this is still the best solution! Wish I knew how to troubleshoot for myself so I didn't have to bug you. Appreciate it a lot!

**Comment by svanhoutte** [comment]
Glad it works. Enjoy !
Think about sponsoring if you can 
[Buymeacoffee](https://www.buymeacoffee.com/sebastienv)
[Paypal](https://paypal.me/SVanhoutte79?country.x=US&locale.x=en_US)

**Comment by svanhoutte** [comment]
Thanks for the contribution ! really appreciated
