### ISSUE TITLE
Missing bodytype

### ISSUE THREAD

**Issue by crypticro** [svanhoutte/wyze_garmin_sync#13]
I am using the latest docker image and I am getting this error

> Traceback (most recent call last):
> 2023-08-30T10:56:47.038005500Z   File "/wyze_garmin_sync/scale.py", line 47, in <module>
> 2023-08-30T10:56:47.038026800Z     physique_rating=float(scale.latest_records[0].body_type),
> 2023-08-30T10:56:47.038042700Z                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2023-08-30T10:56:47.038052300Z TypeError: float() argument must be a string or a real number, not 'NoneType'

It seems like the body_type is missing in the wyze response although it is defined on a my wyze profile.

**Comment by svanhoutte** [comment]
Hello

What type of scale do you use ?

**Comment by crypticro** [comment]
Model: Wyze Scale S
Firmware Version: 1.0.107

**Comment by svanhoutte** [comment]
Hello 
Could you try to remove the body type and re add it ? 
Thanks

**Comment by crypticro** [comment]
I can't remove the body type. I can only change it to female. I changed it to female and now back to male. Would it only take effect for the next measurement?

**Comment by svanhoutte** [comment]
I assume it would.

**Comment by svanhoutte** [comment]
is it working now ?

**Comment by crypticro** [comment]
No it's still the same issue

**Comment by svanhoutte** [comment]
It should be working now. Pull the new docker image and test

**Comment by crypticro** [comment]
Yes, it working now. Thanks!

**Comment by svanhoutte** [comment]
Think about sponsoring if you can 
[Paypal](https://www.paypal.com/paypalme/SVanhoutte79)
