### ISSUE TITLE
"Unknown device type detected" for Wyze Scale X

### ISSUE THREAD

**Issue by ksarnelli** [svanhoutte/wyze_garmin_sync#14]
Running the docker version.  I have a Wyze Scale X and getting a "Unknown device type detected" error in the log.
Here is the JSON from the log:

`({
	'mac': '<REMOVED>',
	'first_activation_ts': 1693765840000,
	'first_binding_ts': 1693765840000,
	'enr': 'enr_place_holder',
	'nickname': 'Master Bathroom Scale',
	'timezone_name': 'America/New_York',
	'product_model': 'WL_SC3',
	'product_model_logo_url': '',
	'product_type': 'Common',
	'hardware_ver': '0.0.0.0',
	'firmware_ver': '1.0.109',
	'user_role': 1,
	'binding_user_nickname': '<REMOVED>',
	'conn_state': 1,
	'conn_state_ts': 0,
	'push_switch': 1,
	'device_params': {},
	'is_in_auto': 0,
	'event_master_switch': 1,
	'parent_device_mac': '',
	'parent_device_enr': '',
	'binding_ts': 1693767504000,
	'timezone_gmt_offset': -4.0
})`

**Comment by svanhoutte** [comment]
Hello 
It seems the Scale X is not supported yet on the SDK. Could you please open a feature request on [Wyze-SDK](https://github.com/shauntarves/wyze-sdk ) same as what was done for the Scale S. I ll then update the container with the latest SDK and it will work. 
Thanks

**Comment by ksarnelli** [comment]
Will do. Thanks!

**Comment by ksarnelli** [comment]
Just wanted to update to say I added the [request](https://github.com/shauntarves/wyze-sdk/issues/148) last week and am waiting to hear back.  Will post an update here if/when support gets added to Wyze-SDK.

**Comment by svanhoutte** [comment]
I did a pull request on Wyze-SDK to support the scale X. If you want to try

**Comment by svanhoutte** [comment]
i gave it a try on this docker, i can't test as i have no scale X. @ksarnelli let me know if you could try that docker image  svanhoutte/wyzegarminconnect:scaleX and confirm this is working for you ?.

**Comment by ksarnelli** [comment]
Thanks!  I'll test tonight.

**Comment by ksarnelli** [comment]
Tried the scaleX tag and got this error:

> Traceback (most recent call last):
  File "/wyze_garmin_sync/scale.py", line 28, in <module>
    scale = client.scales.info(device_mac= ', '.join({device.mac}))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wyze_sdk/api/devices/scales.py", line 77, in info
    raise WyzeFeatureNotSupportedError('Scale Series X')
wyze_sdk.errors.WyzeFeatureNotSupportedError: Scale Series X is not supported on this device
md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
Traceback (most recent call last):
  File "/wyze_garmin_sync/./2FA.py", line 3, in <module>
    import garth
ModuleNotFoundError: No module named 'garth'
/wyze_garmin_sync /wyze_garmin_sync
file not uploaded

**Comment by svanhoutte** [comment]
Thanks bummer it didn't work first try, could you please provide the start of the mac address ?

**Comment by ksarnelli** [comment]
No worries!

MAC Address:  D0:3F:27:68:XX:XX

I actually don't use Wyze for anything besides this scale, so if it would help I can generate you an API key for testing.

Thanks again!

**Comment by svanhoutte** [comment]
@ksarnelli I made some changes and fixed some bugs could you please do a pull and try again ?

**Comment by ksarnelli** [comment]
It works!  Thanks a ton!  Quick question - for multiple users (when using docker) I guess the best approach is just to run a separate container for each user?

**Comment by svanhoutte** [comment]
yes with different credentials 
Scale X version updated with local repo

**Comment by svanhoutte** [comment]
Scale X is now available in the core WyzeSDK package you can just use the standard tag.

**Comment by ksarnelli** [comment]
> Scale X is now available in the core WyzeSDK package you can just use the standard tag.

Thanks! I'll give it a shot.
