### ISSUE TITLE
0 kg in wyze.last.csv and wyze.fit leading to no update.

### ISSUE THREAD

**Issue by Thatindianbruh** [svanhoutte/wyze_garmin_sync#2]
I'm trying to figure out why nothing was updating in Garmin. I checked and made sure that everything was uploading. I went a little further trying to troubleshoot and downloaded the .fit file and opened it. The columns were weight is supposed to populate shows 0. I checked the awk script and there's a mention of $11 and getting multiplied to convert it into kgs, I corrected that to $51 since that's where the weight is stored. I'm still getting a 0. To try further if I change $11 to lets say $7, I get an output 4lbs and the file does get uploaded with 4lbs. 

Thank you for your time, 
Pratik

**Comment by Thatindianbruh** [comment]
fixed it by changing $11 to $12 at line 14 and referencing $51 after $47 in the awk record at line 12.

**Comment by svanhoutte** [comment]
Hi Thatindianbruh

I had a look today and it seems that Wyze changed multiple fields i had to change Metabolic Age and Muscle mass as well. Now line 12 should look like this (3 last value changed in the second awk)
cat ./test | awk -F\<wyze_sdk.ScaleRecord '{print $2}' | awk -F'[ |/}]'  '{printf $5$7$9$11$13$15$17$34$38$40$49}' > ./test5

There should be no need to change anything in the line 14.

Thanks for using it and let me know if the new change works for you.

**Comment by Thatindianbruh** [comment]
Hey Svanhoutte, 

I'll give your new update a shot! 

I've learned so much about awk from just messing with this project. Thank you again for creating this.

**Comment by Thatindianbruh** [comment]
hey! just ran it all, I see you fixed skeleton mass and that's working correctly, but weight doesn't update. I think I have a solution. 

{printf $5$7$9$11$13$15$17$34$38$40$49}
{printf $5$7$9$11$13$15$17$34$38$40$51}

$49 outputs 0kgs, $49 is the 'user_id' output or '67e29f7f6c6677ee1c00b7xxxxxxxxxx'
$51 outputs weight correctly. 

Thank you for your work.

**Comment by svanhoutte** [comment]
Hi 
For me the $51 doesn't work i have to stay with $49. Which software version your scale is running ? here are the filed i have on my side could you confirm you have the same ? 
[<wyze_sdk.ScaleRecord: {'age': x, 'bmi': x, 'bmr': x, 'body_fat': x, 'body_type': x, 'body_vfr': x, 'body_water': x, 'bone_mineral': x, 'device_id': 'JA.SC.x', 'family_member_id': 'x', 'height': x, 'id': 'x', 'impedance': [x, x, x, x], 'mac': 'x', 'measure_ts': x, 'measure_type': x, 'metabolic_age': x, 'muscle': x.7, 'protein': x.4, 'timezone': 'x', 'user_id': 'x', 'weight': x.39}>

thanks

**Comment by Thatindianbruh** [comment]
hey 

Scale is running firmware 2.0.6 

[<wyze_sdk.ScaleRecord: {'age': x, 'bmi': x, 'bmr': x, 'body_fat': x, 'body_type': x, 'body_vfr': x, 'body_water': x, 'bone_mineral': x, 'device_id': 'JA.SC2.x', 'family_member_id': 'x', 'height': x 'id': 'x', 'impedance': [x, x, x, x], 'mac': 'x', 'measure_ts': x, 'measure_type': x, 'metabolic_age': x, 'muscle': x, 'occupation': x, 'protein': x, 'timezone': 'x, 'user_id': 'x', 'weight': x}>

turns out I have an extra data point called 'occupation' and my device id different. JA.SC2

thanks

**Comment by esmoyer** [comment]
Just to help anyone else that may have an issue, I ended up needing to change mine to: `$5$7$9$11$13$15$17$34$36$38$49`

So my line is:
`cat ./test | awk -F\<wyze_sdk.ScaleRecord '{print $2}' | awk -F'[ |/}]'  '{printf $5$7$9$11$13$15$17$34$36$38$49}' > ./test5`

Otherwise a couple fields had the wrong data.
