### ISSUE TITLE
Uploads stopped happening

### ISSUE THREAD

**Issue by papakpmartin** [svanhoutte/wyze_garmin_sync#24]
I've been successfully running `svanhoutte/wyzegarminconnect:latest` in Docker for months. About a week ago scale readings stopped getting sent to Garmin.

The logs look something like this:

```
2024-12-04T03:30:03.775729483Z 2024-12-03 21:30:01: Unknown device type detected ({...'product_type': 'ChimeSensor',...})
2024-12-04T03:30:06.311944153Z Scale found with MAC JA.SC.BLAH. Latest record is:
2024-12-04T03:30:06.312831291Z [<wyze_sdk.ScaleRecord: {...various properties then... 'weight': 174.83}>, <wyze_sdk.ScaleRecord: {...various properties then... 'weight': 176.33}>]
2024-12-04T03:30:06.312958734Z Body Type: 6
2024-12-04T03:30:06.313003363Z Generating fit data...
2024-12-04T03:30:06.316695319Z Fit data generated...
2024-12-04T03:30:06.317426200Z No new measurement
```

Despite there being records, nothing is getting uploaded.

One observation: To fill in the missing weigh-ins, I exported from Wyze and ran it through my [notebook](https://github.com/papakpmartin/wyze-garmin-notebooks) to create the .fit file, and I noticed that the Wyze export now has `Weight(lb)` and `Weight(kg)`, where it used to simply be `Weight` and was in lbs. Maybe something has changed in the data coming from Wyze to this script, too?

Second observation: When I was originally trying to fix this, I re-pulled the image, but it looks like your `:latest` is broken... missing entrypoint.sh. I'm running `:slim-3` right now.

Last observation: I've `rm wyze_scale.fit cksum.txt` to see if that gives it a fresh start. Will let you know if that changes anything.

**Comment by svanhoutte** [comment]
Hi, 

the latest is working for me, what issue are you getting ? are you building the image ? the slim-3 is old i moved to the python:alpine image to reduce the size of the container. What is the hardware you are running on ? 
The cksum.txt is automatically wiped when you reload the docker it is not in a persistent volume.  Maybe clear the tokens and start from scratch with the authentication "docker compose run --rm wyzegarminconnect". 
Let me know i m sure we will make it work.

**Comment by svanhoutte** [comment]
I confirm there is an issue, it seems the authentication is not working anymore using the token. Checking.

**Comment by papakpmartin** [comment]
Happy to try to help... lemme know if there's something I can grab for you.

**Comment by papakpmartin** [comment]
In case it's helpful, it does appear that I have valid Garmin tokens with appropriate scope.

**Comment by papakpmartin** [comment]
FYI https://github.com/matin/garth/issues/73

**Comment by papakpmartin** [comment]
Since garth created a new release addressing that issue, I tried simply recreating the container (using latest this time) assuming that new garth would get imported. Looks like it's working fine now. Presuming this can be closed.

**Comment by svanhoutte** [comment]
Yes I saw that this morning and kicked off an image creation. I ll test it
tonight and confirm.

**Comment by svanhoutte** [comment]
I confirm with garth updated all is working fine.
