### ISSUE TITLE
No Update Happening

### ISSUE THREAD

**Issue by esmoyer** [svanhoutte/wyze_garmin_sync#3]
Hi, glad to have found this script, thanks for creating it. I am having an issue with everything seeming to go fine when running the script, but nothing gets updated in Garmin Connect. I open the CSV and it shows 0 as the weight. There are not errors when running it, so I am not quite sure what the deal might be. Any insight on what I should check to start troubleshooting?

**Comment by svanhoutte** [comment]
Hi,
Try to check the "test" file, cat ./test
If the test file is filed correctly then the api call to wyze is working well. If not then there is issue there. 
then try to check the "test5" file cat./test5
then if you have a 0 in there that would mean there is an issue in the alignment of the fields from test to test5. This would be done in this line 
cat ./test | awk -F\<wyze_sdk.ScaleRecord '{print $2}' | awk -F'[ |/}]'  '{printf $5$7$9$11$13$15$17$34$38$40$49}' > ./test5
in the code the script. 
Happy to to check if you provide test and test5 files. 
Seb

**Comment by esmoyer** [comment]
Thanks for the reply. It appears everything is populating correctly in the "test" file and I am not seeing any "0" in the "test5" file:

```
26.529913,-1.0,-1.0,4,-1,-1.0,-1.0,1665940588319,-1,-1.0,'ca36e9c3bcd5f8c47b94a08a925e1e18',
```

I also just tried to weigh myself again and ran the script and now it's suddenly working! No clue, what the deal was but will close this for now! Thanks again!!

**Comment by svanhoutte** [comment]
Glad it is working now. let me know if it fails again

**Comment by esmoyer** [comment]
Sorry to bug again, but while me running the script manually works, for the life of me I can't figure out why the cronjob won't run it properly. Everything seems fine but I get this error in the logs when cron runs after I have weighed myself:

```
Oct 18 18:58:06 SVR-DockerVM garminsync[347872]: File is correct.
Oct 18 18:58:06 SVR-DockerVM garminsync[347872]: ./wyze.last.csv: FAILED
Oct 18 18:58:06 SVR-DockerVM garminsync[347872]: md5sum: WARNING: 1 computed checksum did NOT match
Oct 18 18:58:06 SVR-DockerVM garminsync[347872]: FIT CSV Tool - Protocol 2.0 Profile 21.78 Release
Oct 18 18:58:06 SVR-DockerVM garminsync[347872]: ./wyze.1.csv encoded into FIT binary file ./wyze.fit.
Oct 18 18:58:06 SVR-DockerVM garminsync[347872]: fit file created
Oct 18 18:58:06 SVR-DockerVM garminsync[347872]: /home/name/wyzetogarmin/wyze_garmin_sync-main/connect_sync.sh: line 32: gupload: command not found
Oct 18 18:58:06 SVR-DockerVM garminsync[347872]: file uploaded
Oct 18 18:58:06 SVR-DockerVM CRON[347869]: pam_unix(cron:session): session closed for user eric
```
but then subsequent runs yield the following until I weigh myself again:

```
Oct 18 19:00:06 SVR-DockerVM garminsync[348197]: File is correct.
Oct 18 19:00:06 SVR-DockerVM garminsync[348197]: ./wyze.last.csv: OK
Oct 18 19:00:06 SVR-DockerVM garminsync[348197]: no new measurment
```

I have tried deleting the wyze.last and chksum files, I even trashed everything and started over, but nothing seems to work; except for running the script manually. Appreciate any other insight you might have. I'm sure it's something dumb on my end!

**Comment by esmoyer** [comment]
Figured it out...definitely something stupid on my end, it was even in the log I posted above but I completely overlooked it. gupload was not being found with cron but worked fine with me running it manually.

Just had to add `PATH="/home/name/.local/bin:/usr/local/bin:/usr/bin:/bin"` to the script and all is working well!

Thanks again for building this, excited to have it going now!
