### ISSUE TITLE
Pound sign in environment variable values causes truncation

### ISSUE THREAD

**Issue by tknorris** [svanhoutte/wyze_garmin_sync#3]
FYI, If you have a pound sign in any of the environment variables (most likely passwords) your current approach of storing those variables values in /etc/environment for when the cron job runs in the docker container won't work as described here: https://serverfault.com/questions/539730/environment-variable-in-etc-environment-with-pound-hash-sign-in-the-value

As the link says, anything after the # gets stripped off the value when pam reads the /etc/environment file in. Caught me up when my wyze password had a # in it. The initial upload when the docker container would start would work, but then the cronjob runs would fail. I changed the password to remove the # to work around it for now. 

I'm not sure what the best fix is. Perhaps using a login shell and /etc/profile instead? I suppose you could just do a 10 minute sleep in the entry point as well rather than use cron since it's not changeable anyway?

**Comment by svanhoutte** [comment]
Thanks for catching that, i m going to work on it and find a way to avoid this. It seems i could pass the BASH_ENV variable in cron. Will give it a try and upload new docker release if this works.

**Comment by svanhoutte** [comment]
I passing the variable direcly in the cron file now that should work. I updated the Docker container.
