### ISSUE TITLE
Clueless on how to set up

### ISSUE THREAD

**Issue by eueyrunbike** [svanhoutte/wyze_garmin_sync#6]
Hi, I have come across your post for integrating the wyze scale to garmin for a while now and didn't understand it at the time so have been using the fitbit->myfitnesspal->garmin method. It has been very spotty lately and have come across your method again. Unfortunately, I have no idea how to go about it having reread the readme a few times. I'm not familiar with github, python, docker and a lot of the terminology used. Would it be too much to ask for a total newbie tutorial on how to get this going with no experience with these programs? I only got to the two-factor authentication part on the wyze app haha. I googled python and docker compose and have their websites up and the respective download files pulled up. Unfortunately, I have no clue on how to go about continuing the process. Thanks for making this, I'm sure many people are in the same situation and perhaps are like me wanting to take advantage of the project you worked on but not knowing how to get it going. I'd be more than inclined to "buy you a coffee". If it's too complicated for someone like me, I can respect that!

**Comment by svanhoutte** [comment]
Hello 

No problem at all. Let's try to make it work for you. 
What is your os ? Windows ? Linux ?
Did you install Docker already ? If you just install Docker you shouldn t need to have to install python.

**Comment by eueyrunbike** [comment]
Yes, I am on Windows and iOS. I did not, I wasn't exactly sure which one to download. Ok, whatever is the easiest option for the non-technically inclined like myself would probably be best. But, I suppose since you are willing to help me out, whatever option is the best is the way I'll go. I appreciate your help!

**Comment by svanhoutte** [comment]
OK cool You have to follow these steps and install WSL https://learn.microsoft.com/en-us/windows/wsl/install then when it is done you can install docker desktop for [windows https://docs.docker.com/desktop/install/windows-install/ ](https://docs.docker.com/desktop/install/windows-install/#install-docker-desktop-on-windows) 

Then download the docker-compose.yml from the repo and put it in a specific directory. Then open a powershell on windows and go in the directory where you put the docker-compose.yml . Now type "docker-compose up " and you should see things starting to download and if you have put your credentials in the docker-compose.yml it will poll your wyze account and upload data to your garmin account. 
Let me know how it goes and if there is any issue.

**Comment by eueyrunbike** [comment]
OK, so I got all the way to opening a powershell to type "docker-compose up" but it gives me an error:

PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> docker-compose up
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dwyze_garmin_sync%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.

I'm not too sure if I'm supposed to include the quotes in "docker-compose up" or not, but I tried both. Also, I'm not sure if I'm supposed to open docker desktop or not. I did and made a free account, but when I run docker desktop it says "docker desktop stopped..." and just closes after a few seconds. 
This is the whole screen in powershell of what I tried to type in. I don't even know how I remember how to find the directory where I put the docker-compose.yml in, but I think I managed to get that part right?:

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Monica> Documents\GitHub\wyze_garmin_sync
Documents\GitHub\wyze_garmin_sync : The module 'Documents' could not be loaded. For more information, run
'Import-Module Documents'.
At line:1 char:1
+ Documents\GitHub\wyze_garmin_sync
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Documents\GitHub\wyze_garmin_sync:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

PS C:\Users\Monica> cd Documents\GitHub\wyze_garmin_sync
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> docker-compose up
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dwyze_garmin_sync%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> "docker-compose up "
docker-compose up
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> "docker-compose up"
docker-compose up
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> docker-compose up
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dwyze_garmin_sync%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> docker-composeup
docker-composeup : The term 'docker-composeup' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ docker-composeup
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (docker-composeup:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> docker compose up
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dwyze_garmin_sync%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> docker compose up
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dwyze_garmin_sync%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> docker compose up
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dwyze_garmin_sync%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> docker-compose up
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dwyze_garmin_sync%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> "docker-compose up"
docker-compose up
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> docker-compose up
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dwyze_garmin_sync%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> docker-compose up
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dwyze_garmin_sync%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> docker-compose up
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dwyze_garmin_sync%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync> "docker-compose up"
docker-compose up
PS C:\Users\Monica\Documents\GitHub\wyze_garmin_sync>

**Comment by eueyrunbike** [comment]
Alright dude. You are THE MAN! Thanks for figuring out the Wyze->Garmin fiasco. That was a serious headache and annoyance of over a year. I can finally unlink my Fitbit and my fitness pal accounts and delete them because this was their sole purpose. Anyways, the people need to know. Anyone with a Wyze scale and Garmin watch would probably be into this as Garmin users tend to be athletes and metric crazed. I realized going through some Reddit posts that I had commented on one from 45 days ago. This has been on my mind far longer than that though. I also tried many attempts to buy you coffee even created a Link account using two different cards to no avail. I’d happily do it through Venmo or PayPal. Let me know. Thanks again for helping me with the step by step. I probably wouldn’t have figured it out otherwise. Bravo 👏🏼.

**Comment by svanhoutte** [comment]
Thanks your words made my day ! And glad you made it work. Additionally you have way more metrics in this setup than on the fitbit/MFP setup. 
If you still want to support here is the paypal link https://www.paypal.com/paypalme/SVanhoutte79?country.x=US&locale.x=en_US
Thanks again.

**Comment by eueyrunbike** [comment]
I do notice a lag. Is this common? As long as it syncs eventually, it’s still fantastic to me. I noticed right away the added metrics on garmin connect weight. Unfortunately, this morning I have weighed in 3 times and have been constantly opening and closing the Wyze and Connect apps and refreshing them over around 10 min without any updates to Garmin. I know Connect can be spotty at times. Just wondering if the lag was considered normal in your opinion. 👍🏼

**Comment by svanhoutte** [comment]
The lag is totally normal the docker is configured to poll the Wyze account and upload the data every 10 min. Then you just have to weight once, and it will automatically do its job. 10 min was a short enough time to not spam the accounts but at the same time allow a good cadence of update. If you weight multiple time in the 10 min window, then only the last measurement will be uploaded

**Comment by eueyrunbike** [comment]
Sounds good. It’s working solid!
