### ISSUE TITLE
Internet got disconnected for a few days

### ISSUE THREAD

**Issue by eueyrunbike** [svanhoutte/wyze_garmin_sync#7]
Hey man, sorry to bother you. So Comcast is forcing me to buy a new cable modem saying my current one's Dosc 3.0 certification has expired. I'm using my phone as a hot spot at the moment. It seems like the measurements have run into some kind of error not having the same entries as when it was syncing. I wonder if it will fix itself or I need to do something. I still don't have a stable connection yet as my modem hasn't arrived yet. So as soon as I turn off my hotspot from my phone it will disconnect Docker. I've attached a text document with the log of when it started producing errors and the most recent entry with the hotspot reestablishing internet connection. 
Hope it's a simple fix. Thank you!

[wyze garmin sync errors.txt](https://github.com/svanhoutte/wyze_garmin_sync/files/10951419/wyze.garmin.sync.errors.txt)

**Comment by svanhoutte** [comment]
Hi 
Thanks for using the solution, did you try restarting the docker ? did you do a pull of the latest version on docker ? 
The solution should work whatever type of connection you have as long as docker get access to the internet. It seems as per the logs that the DNS resolution is not working. Maybe try this, connect through your hotspot, stop the container, restart it and check if the error is still there. It will take around 10 min for the script to sync your last measurement then i would say stay connected at least 15 min
It should resolve IMHO when your connection will be stable.

**Comment by eueyrunbike** [comment]
I have tried restarting the docker, updating it to the latest version, restarting the computer, and just tried stopping the container and restarting. It appears the initial attempt after restarting at 10:57am and it's 10 min interval attempt at 11:00am comes back with the same type of errors. I'll give it 15min or more and report back. If nothing, I'll report back when I get the modem up and running which should be within the next couple days.

**Comment by eueyrunbike** [comment]
Just connected the new modem and stopped and restarted the container. It's all good now...very strange. Sorry for the bother. I guess I'll wait it out a little more before reaching out. Otherwise, it's been working pretty flawlessly. Always updates. I'm happy to have it back online. I briefly looked at prices of the Garmin Scale. Much happier with this solution. Thanks again for the support. Cheers!

**Comment by svanhoutte** [comment]
Glad to hear it is working again. Still wonder why the mobile hotspot was
an issue. Also glad you like the script. Sponsor if you can.

**Comment by svanhoutte** [comment]
fixed
