### ISSUE TITLE
Entrypoint Issues

### ISSUE THREAD

**Issue by esmoyer** [svanhoutte/wyze_garmin_sync#8]
I got this added to my other containers but for some reason I am getting `/bin/sh: 1: /wyze_garmin_sync/entrypoint.sh: Permission denied` in the log, but can't seem to figure it out. Since it's not mounting any volumes I don't know what permissions it would need. Any pointers would be appreciated!

**Comment by esmoyer** [comment]
Fixed by cloning the repo and files and manually mounting the volume in the container to the folder; seems to be working now!

**Comment by esmoyer** [comment]
Also, thanks for creating this, I just migrated to a new VM and was trying to setup the manual script I had setup a couple years ago and this made it *way* quicker and easier!

**Comment by svanhoutte** [comment]
Thanks i made some changes in the automatic build and there was an issue related to the rights of the entrypoint script. 
It is fixed now. 
Definitely a long way since the first integration :) glad you like it and use it.

**Comment by esmoyer** [comment]
Awesome! Now I'm kinda wanting to try and use this as a template to try and dockerize the Garmin2InfluxDB script I use as well. Thanks again!

**Comment by svanhoutte** [comment]
I m as well looking for a good on prem Garmin dashboard solution. Will look in Garmin2influxdb.
