### ISSUE TITLE
Unable to complete run

### ISSUE THREAD

**Issue by johnjohnjohn3** [svanhoutte/wyze_garmin_sync#9]
Hello, I am having trouble getting this to run on a raspberry pi 4.   I am running with the PI user.  I updated both usernames/passwords and TOTP in the legacy file and the docker yml but both methods fail for me.  Updated to the 3.8 python, lateste pip3, and docker.
Docker compose up runs with the following output.  It seems to have permissions issues.  I tried "sudo -s" and tried running "sudo docker compose up"

root@ender3:/home/pi# docker compose logs
pi-wyzegarminconnect-1  | touch: setting times of '/etc/cron.d/garmin_wyze_scheduler': Operation not permitted
pi-wyzegarminconnect-1  | /wyze_garmin_sync /wyze_garmin_sync
pi-wyzegarminconnect-1  | Traceback (most recent call last):
pi-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 4, in <module>
pi-wyzegarminconnect-1  |     import wyze_sdk
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/__init__.py", line 1, in <module>
pi-wyzegarminconnect-1  |     import logging
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
pi-wyzegarminconnect-1  |     _startTime = time.time()
pi-wyzegarminconnect-1  |                  ^^^^^^^^^^^
pi-wyzegarminconnect-1  | PermissionError: [Errno 1] Operation not permitted
pi-wyzegarminconnect-1  | md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
pi-wyzegarminconnect-1  | Traceback (most recent call last):
pi-wyzegarminconnect-1  |   File "/usr/local/bin/gupload", line 5, in <module>
pi-wyzegarminconnect-1  |     from garmin_uploader.cli import main
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/garmin_uploader/__init__.py", line 1, in <module>
pi-wyzegarminconnect-1  |     import logging
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
pi-wyzegarminconnect-1  |     _startTime = time.time()
pi-wyzegarminconnect-1  |                  ^^^^^^^^^^^
pi-wyzegarminconnect-1  | PermissionError: [Errno 1] Operation not permitted
pi-wyzegarminconnect-1  | file not uploaded
pi-wyzegarminconnect-1  | 1969-12-31 19:00:00: 1969-12-31 19:00:00: /wyze_garmin_sync ~
pi-wyzegarminconnect-1  | /wyze_garmin_sync ~
pi-wyzegarminconnect-1  | Traceback (most recent call last):
pi-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 4, in <module>
pi-wyzegarminconnect-1  |     import wyze_sdk
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/__init__.py", line 1, in <module>
pi-wyzegarminconnect-1  |     import logging
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
pi-wyzegarminconnect-1  |     _startTime = time.time()
pi-wyzegarminconnect-1  |                  ^^^^^^^^^^^
pi-wyzegarminconnect-1  | PermissionError: [Errno 1] Operation not permitted
pi-wyzegarminconnect-1  | Traceback (most recent call last):
pi-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 4, in <module>
pi-wyzegarminconnect-1  |     import wyze_sdk
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/__init__.py", line 1, in <module>
pi-wyzegarminconnect-1  |     import logging
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
pi-wyzegarminconnect-1  |     _startTime = time.time()
pi-wyzegarminconnect-1  |                  ^^^^^^^^^^^
pi-wyzegarminconnect-1  | PermissionError: [Errno 1] Operation not permitted
pi-wyzegarminconnect-1  | md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
pi-wyzegarminconnect-1  | md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
pi-wyzegarminconnect-1  | Traceback (most recent call last):
pi-wyzegarminconnect-1  |   File "/usr/local/bin/gupload", line 5, in <module>
pi-wyzegarminconnect-1  |     from garmin_uploader.cli import main
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/garmin_uploader/__init__.py", line 1, in <module>
pi-wyzegarminconnect-1  |     import logging
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
pi-wyzegarminconnect-1  |     _startTime = time.time()
pi-wyzegarminconnect-1  |                  ^^^^^^^^^^^
pi-wyzegarminconnect-1  | PermissionError: [Errno 1] Operation not permitted
pi-wyzegarminconnect-1  | Traceback (most recent call last):
pi-wyzegarminconnect-1  |   File "/usr/local/bin/gupload", line 5, in <module>
pi-wyzegarminconnect-1  |     from garmin_uploader.cli import main
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/garmin_uploader/__init__.py", line 1, in <module>
pi-wyzegarminconnect-1  |     import logging
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
pi-wyzegarminconnect-1  |     _startTime = time.time()
pi-wyzegarminconnect-1  |                  ^^^^^^^^^^^
pi-wyzegarminconnect-1  | PermissionError: [Errno 1] Operation not permitted
pi-wyzegarminconnect-1  | file not uploaded
pi-wyzegarminconnect-1  | file not uploaded
pi-wyzegarminconnect-1  | touch: setting times of '/etc/cron.d/garmin_wyze_scheduler': Operation not permitted
pi-wyzegarminconnect-1  | /wyze_garmin_sync /wyze_garmin_sync
pi-wyzegarminconnect-1  | Traceback (most recent call last):
pi-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 4, in <module>
pi-wyzegarminconnect-1  |     import wyze_sdk
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/__init__.py", line 1, in <module>
pi-wyzegarminconnect-1  |     import logging
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
pi-wyzegarminconnect-1  |     _startTime = time.time()
pi-wyzegarminconnect-1  |                  ^^^^^^^^^^^
pi-wyzegarminconnect-1  | PermissionError: [Errno 1] Operation not permitted
pi-wyzegarminconnect-1  | md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
pi-wyzegarminconnect-1  | Traceback (most recent call last):
pi-wyzegarminconnect-1  |   File "/usr/local/bin/gupload", line 5, in <module>
pi-wyzegarminconnect-1  |     from garmin_uploader.cli import main
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/garmin_uploader/__init__.py", line 1, in <module>
pi-wyzegarminconnect-1  |     import logging
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
pi-wyzegarminconnect-1  |     _startTime = time.time()
pi-wyzegarminconnect-1  |                  ^^^^^^^^^^^
pi-wyzegarminconnect-1  | PermissionError: [Errno 1] Operation not permitted
pi-wyzegarminconnect-1  | file not uploaded
pi-wyzegarminconnect-1  | 1969-12-31 19:00:00: /wyze_garmin_sync ~
pi-wyzegarminconnect-1  | Traceback (most recent call last):
pi-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 4, in <module>
pi-wyzegarminconnect-1  |     import wyze_sdk
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/__init__.py", line 1, in <module>
pi-wyzegarminconnect-1  |     import logging
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
pi-wyzegarminconnect-1  |     _startTime = time.time()
pi-wyzegarminconnect-1  |                  ^^^^^^^^^^^
pi-wyzegarminconnect-1  | PermissionError: [Errno 1] Operation not permitted
pi-wyzegarminconnect-1  | md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
pi-wyzegarminconnect-1  | Traceback (most recent call last):
pi-wyzegarminconnect-1  |   File "/usr/local/bin/gupload", line 5, in <module>
pi-wyzegarminconnect-1  |     from garmin_uploader.cli import main
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/garmin_uploader/__init__.py", line 1, in <module>
pi-wyzegarminconnect-1  |     import logging
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/logging/__init__.py", line 58, in <module>
pi-wyzegarminconnect-1  |     _startTime = time.time()
pi-wyzegarminconnect-1  |                  ^^^^^^^^^^^
pi-wyzegarminconnect-1  | PermissionError: [Errno 1] Operation not permitted
pi-wyzegarminconnect-1  | file not uploaded

**Comment by svanhoutte** [comment]
Hello John, 
Which version of Raspian are you using ? do you have any other container running on the device ? 
did you follow [this](https://docs.docker.com/engine/install/raspbian/) to install Docker ?

**Comment by johnjohnjohn3** [comment]
Hi Svanhoutte, Thanks much for your help and efforts in this.
I am on Rasbian VERSION="10 (buster)" from a Klipper install with kiauh.
I only installed docker for wyze_garmin_sync.  I first installed from the website then removed/reinstalled with your link.  I have Docker version 24.0.2 with Compose version v2.18.1  My only container is svanhoutte/wyzegarminconnect:latest.
I also updated to python 3.8.17 for this.
I am logged in with pi user and i created the docker group per the post-install instructions.
I am currently trying the upgrade to raspbian v11 bullseye to see if it helps.....

**Comment by svanhoutte** [comment]
Hey John 
do you still have the issue with the latest docker install  ? Same issue ?

**Comment by johnjohnjohn3** [comment]
Everything is updated Raspbian11 bulllseye
Docker 24.0.3
compose 2.19.1
python 3.9.2
I verified my logins to both sites.
![image](https://github.com/svanhoutte/wyze_garmin_sync/assets/81889818/d7926829-1eae-47ef-91a0-6f0df9653f0d)

Now I get this output.
pi@ender3:~ $ docker compose up
[+] Running 1/1
 ✔ Container pi-wyzegarminconnect-1  Recreated                                                0.3s
Attaching to pi-wyzegarminconnect-1
pi-wyzegarminconnect-1  | /wyze_garmin_sync /wyze_garmin_sync
pi-wyzegarminconnect-1  | Traceback (most recent call last):
pi-wyzegarminconnect-1  |   File "/wyze_garmin_sync/scale.py", line 17, in <module>
pi-wyzegarminconnect-1  |     client = Client(email=os.environ['WYZE_EMAIL'], password=os.environ['WYZE_PASSWORD'], totp_key=os.environ['WYZE_TOTP'])
pi-wyzegarminconnect-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/api/client.py", line 66, in __init__
pi-wyzegarminconnect-1  |     self.login()
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/api/client.py", line 164, in login
pi-wyzegarminconnect-1  |     response = self._auth_client().user_login(email=self._email, password=self._password, totp_key=self._totp_key)
pi-wyzegarminconnect-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/wyze_sdk/service/auth_service.py", line 83, in user_login
pi-wyzegarminconnect-1  |     verification_code = totp(totp_key)
pi-wyzegarminconnect-1  |                         ^^^^^^^^^^^^^^
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/mintotp.py", line 20, in totp
pi-wyzegarminconnect-1  |     return hotp(key, int(time.time() / time_step), digits, digest)
pi-wyzegarminconnect-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/site-packages/mintotp.py", line 11, in hotp
pi-wyzegarminconnect-1  |     key = base64.b32decode(key.upper() + '=' * ((8 - len(key)) % 8))
pi-wyzegarminconnect-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/base64.py", line 254, in b32decode
pi-wyzegarminconnect-1  |     return _b32decode(_b32alphabet, s, casefold, map01)
pi-wyzegarminconnect-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pi-wyzegarminconnect-1  |   File "/usr/local/lib/python3.11/base64.py", line 236, in _b32decode
pi-wyzegarminconnect-1  |     raise binascii.Error('Non-base32 digit found') from None
pi-wyzegarminconnect-1  | binascii.Error: Non-base32 digit found
pi-wyzegarminconnect-1  | md5sum: /wyze_garmin_sync/cksum.txt: No such file or directory
pi-wyzegarminconnect-1  | 2023-07-06 15:05:52,850 [WARNING] File '/wyze_garmin_sync/wyze_scale.fit' does not exist. Skipping...
pi-wyzegarminconnect-1  | Error: No valid files.
pi-wyzegarminconnect-1  | file not uploaded
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Stopping 1/1
 ✔ Container pi-wyzegarminconnect-1  Stopped                                                 10.3s
canceled

**Comment by svanhoutte** [comment]
It seems a credential issue, do you have the docker-compose.yml in the same folder where you are running the docker compose up  ?

**Comment by johnjohnjohn3** [comment]
It's in /home/pi/
I am running it there.

**Comment by svanhoutte** [comment]
could you do a `docker ps` ?
you should get an output like that :
```
CONTAINER ID   IMAGE                                     COMMAND                  CREATED        STATUS                PORTS                                                                                                                                                                        NAMES
1589df524bc4   svanhoutte/wyzegarminconnect:latest       "/bin/sh -c /wyze_ga…"   23 hours ago   Up 23 hours                                                                          

```
then run `docker exec -it "container id from above" bash` 

You ll be in the container after that, please do a `printenv` to show what are the environment variable. 

don't worry will get there.

**Comment by johnjohnjohn3** [comment]
The "docker compile up" command freezes and requires CTRL-C to exit.  So I left it running in one terminal and ran the above commands in another terminal to get this.
![printenv](https://github.com/svanhoutte/wyze_garmin_sync/assets/81889818/476bb7f7-3d45-4b99-a7f6-90e839084f3e)

**Comment by svanhoutte** [comment]
Hello John

Please try to start from scratch on the Docker with the API key/ID from Wyze and the new docker-compose.yml (cf readme)
Let me know how it goes.
